# Generated by Django 4.1.3 on 2022-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=255)),
                ('descricao', models.TextField(max_length=5000)),
                ('preco', models.IntegerField(default=0)),
                ('qtd_produto', models.IntegerField(default=0)),
            ],
        ),
    ]
